# Generated by Django 4.1.4 on 2023-08-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100)),
                ('claims', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
