# Generated by Django 4.1.4 on 2023-08-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0002_claims'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Claims',
        ),
    ]
