# Generated by Django 4.2.4 on 2023-09-13 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0005_claims_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('question_description', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('response', models.TextField()),
                ('submission_timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_attachment', models.ImageField(default='images/placeholder_img.jpg', upload_to='images/tickets/')),
                ('support_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
