# Generated by Django 4.1.4 on 2023-10-09 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0007_alter_ticket_support_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
