# Generated by Django 4.2.4 on 2023-10-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0008_claims_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image_attachment',
        ),
    ]
